# Generated by Django 4.0.5 on 2022-06-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_contato_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/'),
        ),
    ]
